$(function(){
  $('.menu').hover(function(){
    $(this).find('a').toggleClass('menu-hover')
  })
  $('.readmore').hover(function(){
    $(this).toggleClass('readmore-hover')
  })
  $('.pic').hover(function(){
    $(this).toggleClass('pic-hover')
  })
  $('.twitter').hover(function(){
    $(this).toggleClass('twitter-hover')
  })
  $('.facebook').hover(function(){
    $(this).toggleClass('facebook-hover')
  })
  $('.googleplus').hover(function(){
    $(this).toggleClass('googleplus-hover')
  })
  $('.pinterest').hover(function(){
    $(this).toggleClass('pinterest-hover')
  })
  $('.a').hover(function(){
    $(this).toggleClass('a-hover')
  })
  $('.gallery-pic').hover(function(){
    $(this).toggleClass('pic-hover')
  })
  $('.readthis').hover(function(){
    $(this).toggleClass('readthis-hover')
  })
  $('.send').hover(function(){
    $(this).toggleClass('send-hover')
  })
})